{% set name = "pardiso4py" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pypardiso/pypardiso-{{ version }}.tar.gz
  sha256: 4bf010b55b7a3e6dafefaff9e68794e60b197e473ce008a4b7223c4baa6189c2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mkl
    - numpy
    - libblas =*=*mkl
    - scipy
    - mkl-service
    - psutil

test:
  imports:
    - pypardiso

about:
  home: https://github.com/ma-sadeghi/pardiso4py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations
  dev_url: https://github.com/ma-sadeghi/pardiso4py

extra:
  recipe-maintainers:
    - ma-sadeghi
