{% set name = "pypardiso" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41cb729c1fa9e69393d2f1d73f8758282f34a553ef333ad165f3fd41447518db

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mkl
    - numpy
    - "libblas =*=*mkl"
    - scipy
    - mkl-service
    - psutil

test:
    imports:
    - pypardiso

about:
  home: https://github.com/ma-sadeghi/pardiso4py
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python interface to the Intel MKL Pardiso library to solve large sparse linear systems of equations'
  dev_url: https://github.com/ma-sadeghi/pardiso4py

extra:
  recipe-maintainers:
    - ma-sadeghi
